"""empty message

Revision ID: d68037c0a12d
Revises: 
Create Date: 2025-10-24 20:06:22.425349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68037c0a12d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['activity.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('building',
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('-180 <= longitude AND longitude <= 180', name='ck_building_lon_range'),
    sa.CheckConstraint('-90 <= latitude AND latitude <= 90', name='ck_building_lat_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('corporation',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporation_building_id'), 'corporation', ['building_id'], unique=False)
    op.create_index(op.f('ix_corporation_name'), 'corporation', ['name'], unique=False)
    op.create_table('corporation_activity_link',
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('corporation_id', 'activity_id')
    )
    op.create_table('corporation_phones',
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'phone_number', name='uq_phone_per_corporation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corporation_phones')
    op.drop_table('corporation_activity_link')
    op.drop_index(op.f('ix_corporation_name'), table_name='corporation')
    op.drop_index(op.f('ix_corporation_building_id'), table_name='corporation')
    op.drop_table('corporation')
    op.drop_table('building')
    op.drop_table('activity')
    # ### end Alembic commands ###
